### ISSUE TITLE
Please update the bower version

### ISSUE THREAD

**Issue by w-green** [toddmotto/lunar#4]
This is very a useful. Thank you.

The current bower version points to 1.0.0. Please update to latest.

**Comment by nonmanifold** [comment]
+1

**Comment by davidrapson** [comment]
+1 Any chance of adding a new tag for 1.1.0?

**Comment by toddmotto** [comment]
Guys, added `v1.1.0`, sorry for the delay.

**Comment by maderapson** [comment]
:star2: Thank you
