### ISSUE TITLE
Seems to only work on first selector

### ISSUE THREAD

**Issue by andile2012** [toddmotto/lunar#7]
Thanks for this great library!
I'm wanting to use this with an SVG that contains five buttons, acting like tabs. The 
`lunar.toggleClass(svg, 'active');`
Only seems to work on the first selector of the five. Have any tips?
Thanks!

**Comment by toddmotto** [comment]
Hey @andile2012 - that's right yeah, it doesn't work like jQuery.

What you'll need to do is something like this:

```js
var elements = document.querySelectorAll(<SVG selector>);
for (var i = 0; i < elements.length; i++) {
  lunar.toggleClass(elements[i], 'active');
}
```

This way you loop through each Node you want and toggle the className :)

**Comment by andile2012** [comment]
Thanks, @toddmotto! Here's what I ended up using:
 `
                var elements = document.querySelectorAll('.tab');
		for (var i = 0; i < elements.length; i++) {
  			lunar.removeClass(elements[i], 'active');
		}

		var svg = document.querySelector('.'+id);
		lunar.toggleClass(svg, 'active');
`

**Comment by toddmotto** [comment]
Awesome! :) have a great one whatever you're working on!
